export default function quizzes() {
    return( [
      {
        title: "Top 100 Board Games",
        verb: "played",
        selections: [
            "Gloomhaven (2017)",
            "Pandemic Legacy: Season 1 (2015)",
            "Through the Ages: A New Story of Civilization (2015)",
            "Twilight Struggle (2005)",
            "Terraforming Mars (2016)",
            "Star Wars: Rebellion (2016)",
            "Terra Mystica (2012)",
            "Scythe (2016)",
            "Great Western Trail (2016)",
            "7 Wonders Duel (2015)",
            "The Castles of Burgundy (2011)",
            "War of the Ring (Second Edition) (2012)",
            "Caverna: The Cave Farmers (2013)",
            "Puerto Rico (2002)",
            "Agricola (2007)",
            "Mage Knight Board Game (2011)",
            "Arkham Horror: The Card Game (2016)",
            "Blood Rage (2015)",
            "Mansions of Madness: Second Edition (2016)",
            "Viticulture Essential Edition (2015)",
            "Mechs vs. Minions (2016)",
            "Through the Ages: A Story of Civilization (2006)",
            "Star Wars: Imperial Assault (2014)",
            "Concordia (2013)",
            "Orléans (2014)",
            "Power Grid (2004)",
            "Eclipse (2011)",
            "A Feast for Odin (2016)",
            "Food Chain Magnate (2015)",
            "Gaia Project (2017)",
            "Robinson Crusoe: Adventures on the Cursed Island (2012)",
            "Brass: Lancashire (2007)",
            "Kingdom Death: Monster (2015)",
            "Le Havre (2008)",
            "Tzolk'in: The Mayan Calendar (2012)",
            "Android: Netrunner (2012)",
            "The 7th Continent (2017)",
            "The Voyages of Marco Polo (2015)",
            "Pandemic Legacy: Season 2 (2017)",
            "Keyflower (2012)",
            "7 Wonders (2010)",
            "Codenames (2015)",
            "T.I.M.E Stories (2015)",
            "Caylus (2005)",
            "Eldritch Horror (2013)",
            "Twilight Imperium (Third Edition) (2005)",
            "Race for the Galaxy (2007)",
            "Lords of Waterdeep (2012)",
            "Dominant Species (2010)",
            "Five Tribes (2014)",
            "El Grande (1995)",
            "Fields of Arle (2014)",
            "Patchwork (2014)",
            "Dominion: Intrigue (2009)",
            "Roll for the Galaxy (2014)",
            "Clank!: A Deck-Building Adventure (2016)",
            "Star Wars: X-Wing Miniatures Game (2012)",
            "Dead of Winter: A Crossroads Game (2014)",
            "Battlestar Galactica: The Board Game (2008)",
            "Sherlock Holmes Consulting Detective: The Thames Murders & Other Cases (1981)",
            "Mombasa (2015)",
            "Twilight Imperium: Fourth Edition (2017)",
            "Trajan (2011)",
            "Troyes (2010)",
            "Russian Railroads (2013)",
            "Tigris & Euphrates (1997)",
            "Dominion (2008)",
            "The Gallerist (2015)",
            "Pandemic (2008)",
            "Santorini (2016)",
            "Clans of Caledonia (2017)",
            "Crokinole (1876)",
            "Descent: Journeys in the Dark (Second Edition) (2012)",
            "Kemet (2012)",
            "Castles of Mad King Ludwig (2014)",
            "Stone Age (2008)",
            "War of the Ring (First Edition) (2004)",
            "Alchemists (2014)",
            "Azul (2017)",
            "A Game of Thrones: The Board Game (Second Edition) (2011)",
            "The Resistance: Avalon (2012)",
            "Forbidden Stars (2015)",
            "Arcadia Quest (2014)",
            "Legendary Encounters: An Alien Deck Building Game (2014)",
            "Star Realms (2014)",
            "Ora et Labora (2011)",
            "Anachrony (2017)",
            "Ticket to Ride: Europe (2005)",
            "Nations (2013)",
            "Suburbia (2012)",
            "Istanbul (2014)",
            "Chaos in the Old World (2009)",
            "Commands & Colors: Ancients (2006)",
            "Railways of the World (2005)",
            "Pandemic Iberia (2016)",
            "Captain Sonar (2016)",
            "Paths of Glory (1999)",
            "Spirit Island (2017)",
            "Cosmic Encounter (2008)",
            "Combat Commander: Europe (2006)"
        ]
      },
      {
        title: "Top 100 Movies",
        verb: "seen",
        selections: ["Citizen Kane", "No Country For Old Men", "Groundhog Day"]
      }
    ])
}